# Generated by Django 3.2.16 on 2023-07-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='ip_address',
            field=models.CharField(max_length=255),
        ),
    ]
